FROM python:3.11

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED True

ENV PORT 5000

ENV DB_URL "host=/run/postgresql"
ENV SERVER_ID "lost-server"

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN pip install -e .

CMD exec lost-server start
